### PR TITLE
Add news ticker banner to main page

### PR DESCRIPTION
**Pull request by ggydush**
Changes:
- Added a banner and added some information using `ADAPools` public API! All the information [here](https://js.adapools.org/pools/abea730f5c32157c76c876597d0b7093d50754d0274d67c62d7434b9/summary.json) is fair game, so let me know if there are other things you'd like to add to the banner! Adding more fields shouldn't be too bad, but will take a little tinkering to get the CSS right! So far, I've added:
  - Current epoch
  - Lifetime blocks
  - Total staked (ADA & USD)
  - Current ADA price in USD
- Fixed table so it doesn't overflow and mess up view for mobile
- Added pool parameters section to show our variable fee

As always, check it out live at: http://maestro-stake-pool-dev.surge.sh/

### CODE REVIEW

**Review by MarvinBertin — APPROVED** [review]
Looks geat, love it!

**Review by Vardominator — APPROVED** [review]
so perfect!

**Comment by Vardominator** [comment]
I don't see the banner on mobile, though. Is this intentional?

**Review by apatel-fn — APPROVED** [review]
Looked sick!

**Comment by ggydush** [comment]
> I don't see the banner on mobile, though. Is this intentional?

Confirmed that it on mobile, just a subsequent PR had been deployed on the dev site!

**Pull request merged**
